"""
Django settings for bank_accounts project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&8sx87k!o#3w_quvc)em7-eukndh8(gt52g*dgumn#5k7(9+ee'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'bank_accounts',
    'bank_accounts.accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bank_accounts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank_accounts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
        'CONN_MAX_AGE': 5 * 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


# Authentication

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login'


# IBAN

IBAN_COUNTRIES = [
    ('AL', 28),
    ('AD', 24),
    ('AT', 20),
    ('AZ', 28),
    ('BH', 22),
    ('BY', 28),
    ('BE', 16),
    ('BA', 20),
    ('BR', 29),
    ('BG', 22),
    ('CR', 22),
    ('HR', 21),
    ('CY', 28),
    ('CZ', 24),
    ('DK', 18),
    ('DO', 28),
    ('SV', 28),
    ('EE', 20),
    ('FO', 18),
    ('FI', 18),
    ('FR', 27),
    ('GE', 22),
    ('DE', 22),
    ('GI', 23),
    ('GR', 27),
    ('GL', 18),
    ('GT', 28),
    ('HU', 28),
    ('IS', 26),
    ('IQ', 23),
    ('IE', 22),
    ('IL', 23),
    ('IT', 27),
    ('JO', 30),
    ('KZ', 20),
    ('XK', 20),
    ('KW', 30),
    ('LV', 21),
    ('LB', 28),
    ('LI', 21),
    ('LT', 20),
    ('LU', 20),
    ('MK', 19),
    ('MT', 31),
    ('MR', 27),
    ('MU', 30),
    ('MD', 24),
    ('MC', 27),
    ('ME', 22),
    ('NL', 18),
    ('NO', 15),
    ('PK', 24),
    ('PS', 29),
    ('PL', 28),
    ('PT', 25),
    ('QA', 29),
    ('RO', 24),
    ('LC', 32),
    ('SM', 27),
    ('ST', 25),
    ('SA', 24),
    ('RS', 22),
    ('SC', 31),
    ('SK', 24),
    ('SI', 19),
    ('ES', 24),
    ('SE', 24),
    ('CH', 21),
    ('TL', 23),
    ('TN', 24),
    ('TR', 26),
    ('UA', 29),
    ('AE', 23),
    ('GB', 22),
    ('VG', 24),
]
